# xset -b b 0
# faux-OHMYZSH config
DISABLE_AUTO_UPDATE=true

source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
antidote load

# source <(antibody init)
# antibody bundle < $HOME/.zsh_plugs

# disable software flow control
stty -ixon
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select
zstyle :compinstall filename '/home/fred/.zshrc'

autoload -Uz compinit
compinit

# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob nomatch nocaseglob dotglob
setopt share_history
unsetopt beep
# End of lines configured by zsh-newuser-install
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export GPG_TTY=$(tty)

# # add android studio to path
export PATH=$PATH:$HOME/.local/android-studio/bin

# add Rust to path env
export PATH=$PATH:$HOME/.cargo/bin

# add Flutter to path
export PATH=$PATH:$HOME/.local/share/flutter/bin

# Yarn global bin\
export PATH="$PATH:$HOME/.yarn/bin"

# Nim
export PATH="$PATH:$HOME/Source/Nim/bin"

# add rbenv to path
#export PATH="$HOME/.rbenv/bin:$PATH"

export N_PREFIX=$HOME/.n
export PATH="$PATH:$N_PREFIX/bin"

export PATH="$PATH:$HOME/.local/bin"

if [ -n "$DESKTOP_SESSION" ];then
  eval $(gnome-keyring-daemon --start)
  export SSH_AUTH_SOCK
fi

BASE16_SHELL=$HOME/.config/base16-shell
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias python="python3"

alias hch="git add CHANGELOG.md && git commit -m 'add changelog entry'"

alias vimconf="nvim /home/fred/.vim/vimrc"
alias vimplug="nvim +PlugInstall +PlugClean +qa"
alias vimupd="nvim +PlugUpdate +qa"

alias gr="grep -r -i"

alias gpsu="git push --set-upstream origin"
alias gbm="git branch --merged"
alias gf!="git fetch --prune"
alias gacp="git am --show-current-patch"
alias gpr="git push && open-pr"
alias gprm="git push && open-pr master"
alias gprd="git push && open-pr $(git_develop_branch)"
alias grbim="git rebase -i master"
alias grbid="git rebase -i develop"

alias gop="git-open"
alias goom="gop origin master"

# wholesome mode activate
alias please="sudo"

alias zshconf="nvim /home/fred/.zshrc"
alias xup="xrdb /home/fred/.Xresources"

alias yl="ga yarn.lock && gcmsg \"yarn.lock\""

alias adroid="adbfs /mnt/droid"
alias udroid="fusermount -u /mnt/droid"

alias rails="bundle exec rails"
alias rake="bundle exec rake"
alias rspec="bundle exec rspec"

alias rff="rake test_failfast"
alias rs="rails server"
alias rc="rails console"
alias rdb="rails db"
alias rdm="rails db:migrate"

alias dc="docker-compose"
alias dcu="dc up"
alias dcd="dc down"
alias dcrm="dc rm"

alias rnab="cd android/app/build/outputs/apk/release"
alias undo="grhh HEAD~1"

alias readme="less README.md"

alias compost="composer install && php artisan config:clear && php artisan route:clear && php artisan view:clear && php artisan cache:clear"
alias pest="php artisan test"

alias convertwebp="find ./ -name \"*.webp\" -exec dwebp {} -o {}.png \;; find . -type f -name '*.webp' -delete"


function dkill() {
  docker kill $(docker ps -q)
}

function drm() {
  docker rm $(docker ps -qa)
}

function dbash() {
  docker exec -it $1 /bin/bash
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# add composer to PATH
export PATH=$HOME/.config/composer/vendor/bin:$PATH

# init rbenv
#eval "$(rbenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/fred/.local/share/google-cloud-sdk/path.zsh.inc' ]; then . '/home/fred/.local/share/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/fred/.local/share/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/fred/.local/share/google-cloud-sdk/completion.zsh.inc'; fi


# increase node RAM limit
export NODE_OPTIONS=--max-old-space-size=8192

# DEV KIT
export DEVKITPRO=/opt/devkitpro
export DEVKITARM=${DEVKITPRO}/devkitARM
export DEVKITPPC=${DEVKITPRO}/devkitPPC

export PATH=${DEVKITPRO}/tools/bin:$PATH

