# faux-OHMYZSH config
DISABLE_AUTO_UPDATE=true
ZSH="${HOME}/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"

source <(antibody init)
antibody bundle < $HOME/.zsh_plugs
# disable software flow control
stty -ixon
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select
zstyle :compinstall filename '/home/fred/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob nomatch nocaseglob
unsetopt beep
# End of lines configured by zsh-newuser-install
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# add Rust to path env
export PATH=$PATH:$HOME/.cargo/bin

# add Flutter to path
export PATH=$PATH:$HOME/.local/share/flutter/bin

# Yarn global bin\
export PATH="$PATH:$HOME/.yarn/bin"
#
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export N_PREFIX=$HOME/.n
export PATH="$PATH:$N_PREFIX/bin"

if [ -n "$DESKTOP_SESSION" ];then
  eval $(gnome-keyring-daemon --start)
  export SSH_AUTH_SOCK
fi

BASE16_SHELL=$HOME/.config/base16-shell
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


alias vimconf="nvim /home/fred/.vim/vimrc"
alias vimplug="nvim +PlugInstall +PlugClean +qa"
alias vimupd="nvim +PlugUpdate +qa"

alias gpsu="git push --set-upstream origin"
alias gbm="git branch --merged"
alias gf!="git fetch --prune"
alias gacp="git am --show-current-patch"
alias gpr="git push && open-pr"
alias gprm="git push && open-pr"

# wholesome mode activate
alias please="sudo"

alias zshconf="nvim /home/fred/.zshrc"
alias xup="xrdb /home/fred/.Xresources"

alias yl="ga yarn.lock && gcmsg \"yarn.lock\""

alias adroid="adbfs /mnt/droid"
alias udroid="fusermount -u /mnt/droid"

alias rff="rake test_failfast"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

